apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.network.name }}-covalidator-pvc
  namespace: tdx-apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.resources.storage }}
  storageClassName: local-path

