apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.network.name }}-covalidator
  namespace: tdx-apps
spec:
  selector:
    app: {{ .Values.network.name }}-covalidator
  ports:
  - port: 50055
    targetPort: 50055
    name: grpc
  type: ClusterIP
