apiVersion: v1
kind: ConfigMap
metadata:
  name: tdx-config
data:
  teepod.toml: |
    [server]
    listen_addr = "0.0.0.0:9080"
    
    [cvm]
    cid_start = 20000
    cid_pool_size = 1000
    
    [kms]
    rpc_addr = "kms-service:9043"
    
    [tproxy]
    rpc_addr = "tproxy-service:9070"
    
  kms.toml: |
    [server]
    listen_addr = "0.0.0.0:9043"
    
    [attestation]
    service = "confidential-space"
    
    [cert]
    root_cert_path = "/etc/tdx/certs/root.pem"
    root_key_path = "/etc/tdx/certs/root.key"
    
  tproxy.toml: |
    [server]
    listen_addr = "0.0.0.0:9443"
    rpc_listen_addr = "0.0.0.0:9070"
    
    [wg]
    interface = "tproxy-wg"
    listen_port = 9182
    ip = "10.0.3.1/24"
    
    [cert]
    cert_path = "/etc/tdx/certs/cert.pem"
    key_path = "/etc/tdx/certs/key.pem"
  
  envoy.yaml: |
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 9901
    
    static_resources:
      listeners:
      - name: listener_https
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 9443
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              access_log:
              - name: envoy.access_loggers.file
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                  path: "/dev/stdout"
              route_config:
                name: local_route
                virtual_hosts:
                - name: local_service
                  domains: ["*"]
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: tdx_service
              http_filters:
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
