apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdx-certs
  namespace: tdx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: standard
