apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tdx-kms-role
  namespace: tdx
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tdx-kms-role-binding
  namespace: tdx
subjects:
- kind: ServiceAccount
  name: tdx-kms-sa
  namespace: tdx
roleRef:
  kind: Role
  name: tdx-kms-role
  apiGroup: rbac.authorization.k8s.io
