# service-teepod.yaml
apiVersion: v1
kind: Service
metadata:
  name: teepod-service
  namespace: tdx
spec:
  selector:
    app: teepod
  ports:
  - port: 9080
    targetPort: 9080
  type: ClusterIP
---
# service-kms.yaml
apiVersion: v1
kind: Service
metadata:
  name: kms-service
  namespace: tdx
spec:
  selector:
    app: kms
  ports:
  - port: 9043
    targetPort: 9043
  type: ClusterIP
---
# service-tproxy.yaml
apiVersion: v1
kind: Service
metadata:
  name: tproxy-service
  namespace: tdx
spec:
  selector:
    app: tproxy
  ports:
  - name: https
    port: 9443
    targetPort: 9443
  - name: rpc
    port: 9070
    targetPort: 9070
  - name: wireguard
    port: 9182
    targetPort: 9182
    protocol: UDP
  type: LoadBalancer
