apiVersion: apps/v1
kind: Deployment
metadata:
  name: evm-indexer
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evm-indexer
  template:
    metadata:
      labels:
        app: evm-indexer
    spec:
      containers:
        - name: evm-indexer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          env:
            - name: CONFIG_PATH
              value: "/etc/eth-indexer/config.toml"
            - name: RUST_LOG
              value: "info"
            - name: RUST_BACKTRACE
              value: "1"
          command: ["/bin/sh"]  # Temporarily override for debugging
          args: 
            - -c
            - |
              ls -la /etc/eth-indexer/
              cat /etc/eth-indexer/config.toml
              echo "Starting indexer..."
              eth-high-perf-indexer
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
          volumeMounts:
            - name: data
              mountPath: /data/eth-indexer
            - name: config
              mountPath: /etc/eth-indexer
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: evm-indexer-data
        - name: config
          configMap:
            name: evm-indexer-config
