apiVersion: apps/v1
kind: Deployment
metadata:
  name: evm-indexer
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evm-indexer
  template:
    metadata:
      labels:
        app: evm-indexer
    spec:
      containers:
        - name: evm-indexer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RPC_ENDPOINT
              value: "{{ .Values.indexer.rpcEndpoint }}"
            - name: BLOCKS_IN_MEMORY
              value: "{{ .Values.indexer.blocksInMemory }}"
            - name: ROTATION_BLOCKS
              value: "{{ .Values.indexer.rotationBlocks }}"
            - name: METRICS_PORT
              value: "{{ .Values.indexer.metricsPort }}"
            - name: DATA_DIR
              value: "/data/eth-indexer"
            - name: START_BLOCK
              value: "{{ .Values.indexer.startBlock }}"
            - name: RUST_LOG
              value: "info"
            - name: RUST_BACKTRACE
              value: "1"
          ports:
            - name: metrics
              containerPort: {{ .Values.indexer.metricsPort }}
          volumeMounts:
            - name: data
              mountPath: /data/eth-indexer
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: evm-indexer-data