apiVersion: v1
kind: Service
metadata:
  name: evm-indexer
  namespace: {{ .Release.Namespace }}
  labels:
    app: evm-indexer
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: evm-indexer
