apiVersion: pkg.crossplane.io/v1beta1
kind: Provider
metadata:
  name: provider-gcp
spec:
  package: crossplane/provider-gcp:v0.39.0
---
# Service account for GCP Provider - stored in Secret Manager or similar
apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: gcp-provider
spec:
  projectID: "697085482582"
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane
      name: gcp-credentials
      key: credentials.json
