apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp
spec:
  package: crossplane/provider-gcp:master
---
apiVersion: gcp.crossplane.io/v1
kind: ProviderConfig
metadata:
  name: gcp-provider
spec:
  projectID: "697085482582"
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane
      name: gcp-credentials
      key: credentials.json
