# Create GCP Service Account for TDX
apiVersion: iam.gcp.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  name: crossplane-tdx-kms
  namespace: crossplane
spec:
  forProvider:
    displayName: "TDX KMS Service Account"
    description: "Service account for TDX Key Management Service"
    projectRef:
      name: "697085482582"
  providerConfigRef:
    name: gcp-provider
---
# Allow Kubernetes service account to act as GCP service account
apiVersion: iam.gcp.crossplane.io/v1alpha1
kind: ServiceAccountPolicy
metadata:
  name: tdx-kms-binding
  namespace: crossplane
spec:
  forProvider:
    serviceAccountRef:
      name: crossplane-tdx-kms
    policy:
      bindings:
        - role: roles/iam.workloadIdentityUser
          members:
            - serviceAccount:697085482582.svc.id.goog[tdx-system/tdx-kms-sa]
  providerConfigRef:
    name: gcp-provider
