# configs/crossplane/tdx/tdx-kms.yaml
# Create a KMS keyring
apiVersion: kms.gcp.crossplane.io/v1alpha1
kind: KeyRing
metadata:
  name: tdx-keyring
  namespace: crossplane-system
spec:
  forProvider:
    location: europe-west4
  providerConfigRef:
    name: gcp-provider
---
# Create a KMS key for encryption/decryption
# Add this to your tdx-kms.yaml file
apiVersion: kms.gcp.crossplane.io/v1beta1
kind: CryptoKey
metadata:
  name: tdx-app-key
  namespace: crossplane-system
spec:
  forProvider:
    keyRingRef:
      name: tdx-keyring
    purpose: ENCRYPT_DECRYPT
    versionTemplate:
      algorithm: GOOGLE_SYMMETRIC_ENCRYPTION
      protectionLevel: HSM  # Consider using HSM for higher security
    # Add a rotation period if desired
    rotationPeriod: 86400s # 90 days
  providerConfigRef:
    name: gcp-provider
