# configs/crossplane/tdx/tdx-kms.yaml
# Create a KMS keyring
apiVersion: kms.gcp.crossplane.io/v1alpha1
kind: KeyRing
metadata:
  name: tdx-keyring
  namespace: crossplane-system
spec:
  forProvider:
    location: europe-west4
  providerConfigRef:
    name: gcp-provider
---
# Create a KMS key for encryption/decryption
apiVersion: kms.gcp.crossplane.io/v1alpha1
kind: CryptoKey
metadata:
  name: tdx-app-key
  namespace: crossplane-system
spec:
  forProvider:
    keyRingRef:
      name: tdx-keyring
    purpose: ENCRYPT_DECRYPT
    versionTemplate:
      algorithm: GOOGLE_SYMMETRIC_ENCRYPTION
      protectionLevel: HSM
  providerConfigRef:
    name: gcp-provider
