# configs/crossplane/tdx/tdx-secret.yaml
# Create a Secret Manager secret container
apiVersion: secretmanager.gcp.crossplane.io/v1beta1
kind: Secret
metadata:
  name: tdx-app-secret
  namespace: crossplane-system
spec:
  forProvider:
    replication:
      automatic: true
  providerConfigRef:
    name: gcp-provider
