apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: system
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.14.1
    chart: external-dns
    helm:
      values: |
        # Match the deployment spec
        provider: coredns
        logLevel: debug
        sources:
          - ingress

        env:
          - name: ETCD_URLS
            value: http://192.168.68.64:2379

        # Match the RBAC rules
        rbac:
          create: true
          clusterRole: true
          additionalPermissions:
            - apiGroups: [""]
              resources: ["services","endpoints","pods"]
              verbs: ["get","watch","list"]
            - apiGroups: ["extensions","networking.k8s.io"]
              resources: ["ingresses"]
              verbs: ["get","watch","list"]
            - apiGroups: [""]
              resources: ["nodes"]
              verbs: ["list"]

        serviceAccount:
          create: true
          name: external-dns

        # Match deployment labels and strategy
        deploymentStrategy:
          type: Recreate

        nameOverride: "external-dns"
        fullnameOverride: "external-dns"

        podLabels:
          app: external-dns

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
