apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: system
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.14.1
    chart: external-dns
    helm:
      values: |
        # Override the default labels
        nameOverride: "external-dns"
        fullnameOverride: "external-dns"

        # Match labels exactly
        commonLabels:
          app: external-dns

        podLabels:
          app: external-dns

        # Override the selector
        selector:
          matchLabels:
            app: external-dns

        # Exactly match container args
        sources:
          - ingress

        provider: coredns
        logLevel: debug

        args:
          - --source=ingress
          - --provider=coredns
          - --log-level=debug

        env:
          - name: ETCD_URLS
            value: http://192.168.68.64:2379

        deploymentStrategy:
          type: Recreate

        # Strip out all probes and security context
        livenessProbe:
          enabled: false
        readinessProbe:
          enabled: false

        securityContext: {}
        podSecurityContext: {}
        containerSecurityContext: {}

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system # Changed to kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
