# applications/dns/externaldns.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: system
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.14.1
    chart: external-dns
    helm:
      values: |
        provider: etcd
        policy: sync
        domainFilters:
          - "home"
        txtOwnerId: "home-cluster"
        sources:
          - ingress
          - service

        etcd:
          endpoints:
            - http://192.168.68.64:2379
          prefix: /skydns

        rbac:
          create: true

        nodeSelector:
          kubernetes.io/hostname: nas
