# applications/dns/externaldns.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: ${argo_cd_namespace}
spec:
  project: system
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: 1.14.1
    helm:
      values: |
        provider: coredns
        domainFilters:
          - "home"
        txtOwnerId: "home-cluster"
        sources:
          - ingress
          - service
        coredns:
          etcdEndpoints: "" # Remove etcd dependency
          corednsPrefix: "" # Remove default /skydns prefix
        policy: sync
        logLevel: debug # Temporarily increase logging
        interval: "1m"
        registry: txt
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

