apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: system
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: 1.14.1
    helm:
      values: |
        provider: coredns
        domainFilters:
          - "home"
        txtOwnerId: "home-cluster"
        sources:
          - ingress
          - service
        coredns:
          host: "coredns.kube-system" # Adjust this to your CoreDNS service name/namespace
          port: 53
          protocol: "dns"
        policy: sync
        logLevel: debug
        interval: "1m"
        registry: txt
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
