apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: system
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.14.1
    chart: external-dns
    helm:
      values: |
        fullnameOverride: "external-dns"

        # Exactly match the working deployment
        deploymentStrategy:
          type: Recreate

        # Match the selector and labels
        selector:
          app: external-dns
        podLabels:
          app: external-dns

        # Match the container configuration
        image:
          repository: registry.k8s.io/external-dns/external-dns
          tag: "v0.15.0"

        args:
          - --source=ingress
          - --provider=coredns
          - --log-level=debug

        env:
          - name: ETCD_URLS
            value: http://192.168.68.64:2379

        # Strip out unnecessary config
        resources: {}
        serviceAccount:
          create: true
          name: external-dns

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
