# applications/dns/externaldns.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: system
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.14.1
    chart: external-dns
    helm:
      values: |
        provider: coredns
        policy: sync
        domainFilters:
          - "home"
        txtOwnerId: "home-cluster"
        sources:
          - ingress
          - service

        extraEnv:
          - name: ETCD_ENDPOINTS
            value: http://192.168.68.64:2379

        # CoreDNS specific configuration
        coredns:
          etcdEndpoints: http://192.168.68.64:2379
          etcdCorednsPrefix: /skydns

        rbac:
          create: true

        nodeSelector:
          kubernetes.io/hostname: nas
