# applications/dns/externaldns.yaml
# applications/dns/externaldns.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: system
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.14.1
    chart: external-dns
    helm:
      values: |
        provider: coredns
        policy: sync
        domainFilters:
          - "home"
        txtOwnerId: "home-cluster"
        sources:
          - ingress
          - service

        # Explicit environment variables for etcd configuration
        env:
          - name: ETCD_URLS
            value: http://192.168.68.64:2379

        # Additional arguments for etcd configuration
        extraArgs:
          - --etcd-urls=http://192.168.68.64:2379
          - --coredns-prefix=/skydns

        rbac:
          create: true

        nodeSelector:
          kubernetes.io/hostname: nas

        tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
