# applications/dns/externaldns.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: system
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.14.1
    chart: external-dns
    helm:
      values: |
        provider: coredns
        policy: sync
        domainFilters:
          - "home"
        txtOwnerId: "home-cluster"
        sources:
          - ingress
          - service
        coredns:
          etcdEndpoints: "http://192.168.68.64:2379"
          etcdCorednsPrefix: "/skydns"

        # RBAC configuration
        rbac:
          create: true
          
        serviceAccount:
          create: true
          name: external-dns
          
        # Additional args for etcd
        extraArgs:
          - --etcd-urls=http://192.168.68.64:2379
          
        # Security context
        podSecurityContext:
          fsGroup: 65534
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65532
          
        nodeSelector:
          kubernetes.io/hostname: nas
          
        tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"

  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
