apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: system
  source:
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.14.9
    chart: metallb
    helm:
      values: |
        # Configure your IP ranges here
        addressPools:
        - name: default
          protocol: layer2
          addresses:
          - 192.168.71.10-192.168.71.250  # Adjust to your network
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true   
