apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argo-system
spec:
  project: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: "7.0.17"
    helm:
      values: |
        adminPassword: superduperadmin  #### to be moved to a k8s secret or something fancier
        persistence:
          enabled: true
          size: 1Gi
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Prometheus
              type: prometheus
              url: http://prometheus-server.monitoring-system.svc.cluster.local
              access: proxy
              isDefault: true
        dashboardsProviders:
          dashboards.yaml:
            apiVersion: 1
            providers:
            - name: 'default'
              orgId: 1
              folder: ''
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/default
        dashboards:
          default:
            kubernetes-cluster:
              gnetId: 6417
              revision: 1
              datasource: Prometheus
            node-exporter:
              gnetId: 1860
              revision: 1
              datasource: Prometheus
            pods-statistics:
              gnetId: 16277
              revision: 1
              datasource: Prometheus
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true