apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argo-system
spec:
  project: system
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: "1.7.1"
    helm:
      values: |
        clusterName: ${module.eks.cluster_name}
        region: ${var.aws_region}
        vpcId: ${module.vpc.vpc_id}
        serviceAccount:
          create: true
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::${local.account_id}:role/AmazonEKSLoadBalancerControllerRole
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 80Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true