# configs/coredns/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  custom.override: |
    home:53 {
        hosts {
            192.168.68.64 nas.home
            fallthrough
        }
        forward . 1.1.1.1 8.8.8.8
        cache 30
        loop
        reload
        log
    }
