apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
            reload 1s
            fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf {
            policy sequential
        }
        cache 30
        loop
        reload 5s
        loadbalance
        log  # Add logging
    }
    home:53 {
        errors
        log  # Add logging
        etcd {
            stubzones
            path /skydns
            endpoint https://192.168.68.64:2379
            tls /etc/coredns/etcd-client/ca.crt /etc/coredns/etcd-client/client.crt /etc/coredns/etcd-client/client.key
            fallthrough
        }
        prometheus :9153
        cache 30
        reload 5s
    }
