apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  home.override: |
    .:53 {
        hosts /etc/coredns/hosts {
            # Static entries for other servers
            192.168.68.64 nas.home
            fallthrough
        }
        forward . 1.1.1.1 8.8.8.8
        cache 30
        loop
        reload
        log
        errors
    }
    home:53 {
        log
        errors
        cache 30
        file /etc/coredns/home.db
        forward . 1.1.1.1 8.8.8.8
    }
