# configs/coredns/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
            reload 1s
            fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf {
            policy sequential
        }
        cache 30
        loop
        reload 5s
        loadbalance
    }
    home:53 {
        etcd {
            path /skydns
            endpoint http://127.0.0.1:2379
        }
        prometheus :9153
        cache 30
        reload 5s
    }resolv.conf {
            policy sequential
        }
        cache 30
        loop
        reload 5s
        loadbalance
    }
    home:53 {
        etcd {
            path /skydns
            endpoint http://127.0.0.1:2379
        }
        prometheus :9153
        cache 30
        reload 5s
    }
