apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
            reload 1s
            fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf {
            policy sequential
        }
        cache 30
        loop
        reload 5s
        loadbalance
        log
    }
    home:53 {
        errors
        log
        etcd {
            path /skydns
            endpoint http://etcd.kube-system.svc.cluster.local:2379
            fallthrough
        }
        # Add hosts file as backup/alternative
        hosts {
            192.168.71.11 minio.home console.minio.home
            192.168.71.12 argocd.home
            fallthrough
        }
        prometheus :9153
        cache 30
        reload 5s
    }
  NodeHosts: |
    127.0.0.1 localhost
