apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom # This is mounted as custom-config-volume
  namespace: kube-system
data:
  custom.server: | # Using .server instead of .override
    home {
        forward . 1.1.1.1 8.8.8.8
    }
