# configs/coredns/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - configmap.yaml
patches:
  - target:
      kind: Deployment
      name: coredns
      namespace: kube-system
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
