apiVersion: v1
kind: Service
metadata:
  name: coredns-external
  namespace: kube-system
  labels:
    k8s-app: kube-dns
spec:
  type: NodePort
  ports:
    - name: dns
      port: 53
      protocol: UDP
      targetPort: 53
      nodePort: 30053
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
      nodePort: 30053
  selector:
    k8s-app: kube-dns
