# configs/minio/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
  namespace: storage
type: Opaque
stringData:
  # These credentials will be used to access MinIO
  # Make sure to change these in a production environment
  accesskey: "miniouser"
  secretkey: "minio123SecurePassword!@#"
