# configs/minio/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: storage
  labels:
    app: minio
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "minio.home,console.minio.home"
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
      name: api
    - port: 9001
      targetPort: 9001
      name: console
  selector:
    app: minio
