apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
  namespace: media
data:
  .env: |
    # Database
    DB_USERNAME=postgres
    DB_PASSWORD_FILE=/run/secrets/immich-db-password
    DB_DATABASE_NAME=mediadb
    DB_HOSTNAME=postgres.data.svc.cluster.local
    
    # Upload location
    UPLOAD_LOCATION=/usr/src/app/upload
    
    # Redis
    REDIS_HOSTNAME=redis.data.svc.cluster.local
    REDIS_PORT=6379
    REDIS_DBINDEX=0
    
    # Server configuration
    NODE_ENV=production
    LOG_LEVEL=info
    IMMICH_MACHINE_LEARNING_ENABLED=true
    IMMICH_SERVER_URL=https://immich.home
    
    # Web interface
    WEB_ROOT=/usr/src/app/www

    # Microservices
    MICROSERVICES_ENDPOINT=http://immich-microservices:3002
    
    # ML Model configurations
    MACHINE_LEARNING_CACHE_FOLDER=/usr/src/app/cache
    MACHINE_LEARNING_ENABLED=true
    MACHINE_LEARNING_WORKERS=1
    
    # S3 configuration
    IMMICH_S3_ENABLED=true
    S3_ENDPOINT=http://192.168.68.64:9000
    S3_BUCKET_NAME=immich
    S3_ACCESS_KEY=admin
    S3_SECRET_KEY_FILE=/run/secrets/immich-minio-secret
    S3_REGION=
    S3_PATH_STYLE=true
