apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-nginx-config
  namespace: media
data:
  nginx.conf: |
    server {
      listen 80;
      
      add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
      client_max_body_size 512M;
      fastcgi_buffers 64 4K;
      
      location / {
        root /var/www/html;
        index index.php index.html;
        try_files $uri $uri/ /index.php$is_args$args;
      }
      
      location ~ \.php$ {
        root /var/www/html;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_read_timeout 300;
      }
    }
