apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: media
spec:
  selector:
    matchLabels:
      app: nextcloud
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:apache
          ports:
            - containerPort: 80
              name: http
          env:
            - name: POSTGRES_HOST
              value: postgres.data.svc.cluster.local
            - name: POSTGRES_DB
              value: mediadb
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: password
            - name: PHP_MEMORY_LIMIT
              value: "512M"
            - name: PHP_UPLOAD_LIMIT
              value: "512M"
          volumeMounts:
            - name: config
              mountPath: /var/www/html/config
            - name: nextcloud-data
              mountPath: /var/www/html/data
            # Mount MinIO buckets to external path
            - name: movies
              mountPath: /mnt/external/movies
            - name: series
              mountPath: /mnt/external/series  
            - name: pictures
              mountPath: /mnt/external/pictures
            - name: configs
              mountPath: /mnt/external/configs
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 512Mi
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    # Wait for Nextcloud to initialize
                    until [ -f /var/www/html/config/config.php ]; do sleep 5; done
                    echo "Nextcloud initialized, creating directory links..."
                    mkdir -p /var/www/html/data/external
                    ln -sf /mnt/external/movies /var/www/html/data/external/movies
                    ln -sf /mnt/external/series /var/www/html/data/external/series
                    ln -sf /mnt/external/pictures /var/www/html/data/external/pictures
                    ln -sf /mnt/external/configs /var/www/html/data/external/configs
                    echo "Symlinks created successfully"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: nextcloud-config-pvc
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-data-pvc
        # Host path volumes pointing to mounted MinIO buckets
        - name: movies
          hostPath:
            path: /mnt/minio/movies
            type: Directory
        - name: series
          hostPath:
            path: /mnt/minio/series
            type: Directory
        - name: pictures
          hostPath:
            path: /mnt/minio/pictures
            type: Directory
        - name: configs
          hostPath:
            path: /mnt/minio/configs
            type: Directory
