apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: media
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      initContainers:
        - name: init-data-dirs
          image: alpine:latest
          command:
            - sh
            - -c
            - |
              mkdir -p /var/www/html/data/external
              chmod 770 /var/www/html/data/external
              echo "Initialization complete"
          volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/html/data
      containers:
        - name: nextcloud
          image: nextcloud:apache
          ports:
            - containerPort: 80
              name: http
          env:
            - name: POSTGRES_HOST
              value: postgres.data.svc.cluster.local
            - name: POSTGRES_DB
              value: mediadb
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-creds
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-creds
                  key: password
            - name: PHP_MEMORY_LIMIT
              value: "512M"
            - name: PHP_UPLOAD_LIMIT
              value: "512M"
            - name: TRUSTED_PROXIES
              value: "10.0.0.0/8 172.16.0.0/12 192.168.0.0/16"
            - name: APACHE_DISABLE_REWRITE_IP
              value: "1"
            - name: OVERWRITEHOST
              value: "nextcloud.home"
            - name: OVERWRITEPROTOCOL
              value: "https"
            - name: REDIS_HOST
              value: "redis.data.svc.cluster.local"
          volumeMounts:
            - name: config
              mountPath: /var/www/html/config
            - name: nextcloud-data
              mountPath: /var/www/html/data
            - name: nextcloud-custom-config
              mountPath: /etc/apache2/sites-available/000-default.conf
              subPath: apache-config.conf
            - name: nextcloud-s3-config
              mountPath: /var/www/html/config/s3.config.php
              subPath: custom.config.php
          startupProbe:
            httpGet:
              path: /status.php
              port: http
            initialDelaySeconds: 30
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /status.php
              port: http
            initialDelaySeconds: 120
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /status.php
              port: http
            initialDelaySeconds: 60
            periodSeconds: 15
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    # Wait for Nextcloud to initialize
                    until [ -f /var/www/html/config/config.php ]; do 
                      echo "Waiting for Nextcloud to initialize..."
                      sleep 10
                    done
                    
                    # Create script to enable S3 external storage
                    cat > /tmp/enable_s3_storage.php << 'EOF'
                    <?php
                    require_once '/var/www/html/lib/base.php';
                    
                    // Wait for full initialization
                    while (!\OC::$server->getSystemConfig()->getValue('installed', false)) {
                      echo "Waiting for Nextcloud to fully initialize...\n";
                      sleep(10);
                    }
                    
                    echo "Nextcloud is fully initialized. Proceeding with app setup...\n";
                    
                    // Get necessary services
                    $appManager = \OC::$server->getAppManager();
                    
                    // Enable external storage app
                    if (!$appManager->isEnabledForUser('files_external')) {
                      echo "Enabling external storage app...\n";
                      $appManager->enableApp('files_external');
                    }
                    
                    // Enable S3 compatibility apps
                    if (!$appManager->isEnabledForUser('files_external_s3')) {
                      echo "Enabling S3 compatibility app...\n";
                      $appManager->enableApp('files_external_s3');
                    }
                    
                    echo "App setup completed!\n";
                    EOF
                    
                    # Wait a bit more to ensure database is fully set up
                    sleep 30
                    
                    # Execute the script
                    php /tmp/enable_s3_storage.php
                    
                    echo "Nextcloud post-initialization complete"
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: nextcloud-config-pvc
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-data-pvc
        - name: nextcloud-custom-config
          configMap:
            name: nextcloud-apache-config
        - name: nextcloud-s3-config
          configMap:
            name: nextcloud-configs
