apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: media
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      securityContext:
        fsGroup: 33  # www-data group
      initContainers:
        - name: wait-for-db
          image: postgres:13-alpine
          command:
            - sh
            - -c
            - |
              echo "Checking if PostgreSQL database exists..."
              until PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -U $POSTGRES_USER -c '\l' | grep -q "$POSTGRES_DB"; do
                echo "Database $POSTGRES_DB does not exist yet. Attempting to create it..."
                PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -U $POSTGRES_USER -c "CREATE DATABASE $POSTGRES_DB;"
                if [ $? -eq 0 ]; then
                  echo "Database $POSTGRES_DB created successfully!"
                  break
                fi
                echo "Could not create database, waiting for database to be available..."
                sleep 5
              done
              echo "Database $POSTGRES_DB exists! Proceeding with NextCloud deployment."
          env:
            - name: POSTGRES_HOST
              value: postgres.data.svc.cluster.local
            - name: POSTGRES_DB
              value: mediadb
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-creds
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-creds
                  key: password
        - name: fix-permissions
          image: alpine:latest
          command:
            - sh
            - -c
            - |
              mkdir -p /var/www/html/data
              chmod 0770 /var/www/html/data
              chown 33:33 /var/www/html/data  # www-data:www-data
              echo "Data directory permissions set to 0770"
          volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/html/data
        - name: configure-s3
          image: nextcloud:apache
          command:
            - sh
            - -c
            - |
              # Create configs directory if it doesn't exist
              mkdir -p /var/www/html/config
              
              # Write S3 configuration before Nextcloud starts
              cat > /var/www/html/config/s3.config.php << 'EOF'
              <?php
              $CONFIG = array (
                'objectstore' => array(
                  'class' => '\\OC\\Files\\ObjectStore\\S3',
                  'arguments' => array(
                    'bucket' => 'nextcloud',
                    'autocreate' => true,
                    'key' => 'admin',
                    'secret' => 'minio123SecurePassword!@#',
                    'hostname' => '192.168.68.64',
                    'port' => 9000,
                    'use_ssl' => false,
                    'use_path_style' => true,
                  ),
                ),
              );
              EOF
              
              echo "S3 primary storage configuration created."
          volumeMounts:
            - name: config
              mountPath: /var/www/html/config
      containers:
        - name: nextcloud
          image: nextcloud:apache
          ports:
            - containerPort: 80
              name: http
          env:
            # Auto-install configuration
            - name: NEXTCLOUD_ADMIN_USER
              value: "admin"
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-admin-creds
                  key: password
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: "nextcloud.home localhost"
            # Database configuration
            - name: POSTGRES_HOST
              value: postgres.data.svc.cluster.local
            - name: POSTGRES_DB
              value: mediadb
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-creds
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-creds
                  key: password
            # PHP and proxy settings
            - name: PHP_MEMORY_LIMIT
              value: "512M"
            - name: PHP_UPLOAD_LIMIT
              value: "512M"
            - name: TRUSTED_PROXIES
              value: "10.0.0.0/8 172.16.0.0/12 192.168.0.0/16"
            - name: APACHE_DISABLE_REWRITE_IP
              value: "1"
            - name: OVERWRITEHOST
              value: "nextcloud.home"
            - name: OVERWRITEPROTOCOL
              value: "https"
            - name: REDIS_HOST
              value: "redis.data.svc.cluster.local"
            # Skip running the installation again if config directory exists
            - name: NEXTCLOUD_UPDATE
              value: "1"
          volumeMounts:
            - name: config
              mountPath: /var/www/html/config
            - name: nextcloud-data
              mountPath: /var/www/html/data
            - name: nextcloud-custom-config
              mountPath: /etc/apache2/sites-available/000-default.conf
              subPath: apache-config.conf
            - name: custom-config
              mountPath: /var/www/html/config/custom.config.php
              subPath: custom.config.php
          startupProbe:
            httpGet:
              path: /status.php
              port: http
            initialDelaySeconds: 120
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /status.php
              port: http
            initialDelaySeconds: 180
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /status.php
              port: http
            initialDelaySeconds: 120
            periodSeconds: 15
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          lifecycle:
            postStart:
              exec:
                command:
                  - bash
                  - -c
                  - |
                    # Wait for Nextcloud to be fully initialized
                    sleep 30
                    
                    # Only run the configuration if the external storage isn't set up yet
                    if ! php /var/www/html/occ app:list | grep -q "files_external"; then
                      # Enable required apps
                      php /var/www/html/occ app:enable files_external || echo "Could not enable files_external"
                      php /var/www/html/occ app:enable files_external_s3 || echo "Could not enable files_external_s3"
                      
                      # Setup external storages
                      echo "Setting up external S3 storage for media buckets..."
                      php /var/www/html/occ files_external:create "Movies" amazons3 amazons3::accesskey \
                        --config bucket=movies \
                        --config hostname=192.168.68.64 \
                        --config port=9000 \
                        --config region=optional \
                        --config use_ssl=false \
                        --config use_path_style=true \
                        --config legacy_auth=false \
                        --config key=admin \
                        --config secret=minio123SecurePassword!@# || echo "Failed to set up Movies bucket"
                      
                      php /var/www/html/occ files_external:create "TV Series" amazons3 amazons3::accesskey \
                        --config bucket=series \
                        --config hostname=192.168.68.64 \
                        --config port=9000 \
                        --config region=optional \
                        --config use_ssl=false \
                        --config use_path_style=true \
                        --config legacy_auth=false \
                        --config key=admin \
                        --config secret=minio123SecurePassword!@# || echo "Failed to set up TV Series bucket"
                      
                      php /var/www/html/occ files_external:create "Pictures" amazons3 amazons3::accesskey \
                        --config bucket=pictures \
                        --config hostname=192.168.68.64 \
                        --config port=9000 \
                        --config region=optional \
                        --config use_ssl=false \
                        --config use_path_style=true \
                        --config legacy_auth=false \
                        --config key=admin \
                        --config secret=minio123SecurePassword!@# || echo "Failed to set up Pictures bucket"
                    fi
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: nextcloud-config-pvc
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-data-pvc
        - name: nextcloud-custom-config
          configMap:
            name: nextcloud-apache-config
        - name: custom-config
          configMap:
            name: nextcloud-configs
            items:
              - key: custom.config.php
                path: custom.config.php
