apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud
  namespace: media
  annotations:
    cert-manager.io/cluster-issuer: "selfsigned-issuer"
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
    external-dns.alpha.kubernetes.io/enabled: "true"
    external-dns.alpha.kubernetes.io/hostname: "nextcloud.home"
    external-dns.alpha.kubernetes.io/ttl: "60"
    # NextCloud specific annotations
    traefik.ingress.kubernetes.io/preserve-host: "true"
    # Increase timeouts for large file uploads
    traefik.ingress.kubernetes.io/request-timeout: "300s"
    # Add required headers
    traefik.ingress.kubernetes.io/headers-middleware: "nextcloud-security-headers"
spec:
  tls:
    - hosts:
        - nextcloud.home
      secretName: nextcloud-tls
  rules:
    - host: nextcloud.home
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextcloud
                port:
                  number: 80
---                    
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: nextcloud-security-headers
  namespace: media
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
    customResponseHeaders:
      X-Content-Type-Options: "nosniff"
      X-XSS-Protection: "1; mode=block"
      Referrer-Policy: "no-referrer"
      X-Frame-Options: "SAMEORIGIN"                    
