apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-db-creds
  namespace: media
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: TmFzU2VydmVyUG9zdGdyZXNkYg==

---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-minio-creds
  namespace: media
type: Opaque
data:
  accessKey: YWRtaW4=
  secretKey: bWluaW8xMjNTZWN1cmVQYXNzd29yZCFAIw==

---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-admin-creds
  namespace: media
type: Opaque
data:
  username: YWRtaW4=
  password: Y2hhbmdlbWUxMjM= 

