image:
  repository: ghcr.io/amunt0/evm-indexer
  tag: latest
  pullPolicy: Always

persistence:
  size: 5Gi
  storageClass: standard

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

metrics:
  port: 9090
