image:
  repository: ghcr.io/amunt0/evm-indexer
  tag: latest
  pullPolicy: Always

persistence:
  size: 5Gi

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

indexer:
  rpcEndpoint: ""          # Will be set in ArgoCD
  blocksInMemory: 1000     # Default value
  rotationBlocks: 10000    # Default value
  metricsPort: 9090       # Default value
  startBlock: 0           # Will be set in ArgoCD

metrics:
  port: 9090
