image:
  repository: ghcr.io/amunt0/evm-indexer
  tag: latest
  pullPolicy: Always

persistence:
  size: 5Gi

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

indexer:
  rpcEndpoint: "http://localhost:8545"
  blocksInMemory: 1000
  rotationBlocks: 10000
  metricsPort: 9090
  startBlock: 20000000

metrics:
  port: 9090
