---
{{- range .Values.networks }}
---
# Network-specific Secret Manager secret
apiVersion: secretmanager.gcp.crossplane.io/v1beta1
kind: Secret
metadata:
  name: {{ .name }}-covalidator-secret
  namespace: crossplane
spec:
  forProvider:
    replication:
      automatic: true
  providerConfigRef:
    name: gcp-provider

---
# Network-specific KMS key
apiVersion: kms.gcp.crossplane.io/v1beta1
kind: CryptoKey
metadata:
  name: {{ .name }}-covalidator-key
  namespace: crossplane
spec:
  forProvider:
    keyRingRef:
      name: tdx-keyring
    purpose: ENCRYPT_DECRYPT
    versionTemplate:
      algorithm: GOOGLE_SYMMETRIC_ENCRYPTION
      protectionLevel: HSM
    rotationPeriod: {{ .rotationPeriod }}
  providerConfigRef:
    name: gcp-provider
{{- end }}
