# configs/tdx-apps/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: covalidator-pvc
  namespace: tdx-apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path  # Changed from 'standard' to 'local-path'
