apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: external-dns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: k8s.gcr.io/external-dns/external-dns:v0.13.1
          args:
            - --source=service
            - --source=ingress
            - --provider=webhook
            - --webhook-provider-url=http://pihole-updater.dns.svc.cluster.local:8080
            - --registry=txt
            - --txt-owner-id=k3s
            - --domain-filter=home
            - --log-level=debug
          volumeMounts:
            - name: config-volume
              mountPath: /etc/external-dns
      volumes:
        - name: config-volume
          configMap:
            name: external-dns-webhook-config
