# configs/external-dns/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: kube-system
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
        - name: external-dns
          image: registry.k8s.io/external-dns/external-dns:v0.15.0
          args:
            - --source=ingress
            - --registry=etcd
            - --etcd-urls=https://192.168.68.64:2379
            - --etcd-ssl-ca=/etc/etcd/ssl/ca.crt
            - --etcd-ssl-cert=/etc/etcd/ssl/client.crt
            - --etcd-ssl-key=/etc/etcd/ssl/client.key

            #    - --provider=coredns
            #- --log-level=debug
            #- --domain-filter=home # Add domain filter
          env:
            - name: ETCD_URLS
              value: http://192.168.68.64:2379
