apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fhevm-indexer
  namespace: argocd
spec:
  project: apps
  source:
    repoURL: https://github.com/amunt0/argocd-apps 
    targetRevision: HEAD
    path: configs/fhevm-indexer/
    helm:
      values: |
        image:
          repository: ghcr.io/amunt0/evm-processor
          tag: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: fhevm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
