apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-config
  namespace: ${argo_cd_namespace}
spec:
  project: system
  source:
    repoURL: https://github.com/amunt0/argocd-apps
    targetRevision: HEAD
    path: configs/cert-manager
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
