apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etcd
  namespace: argocd
spec:
  project: system
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 11.0.8
    chart: etcd
    helm:
      values: |
        auth:
          rbac:
            enabled: false
          client:
            secureTransport: false
            enableAuthentication: false
        service:
          type: ClusterIP
          port: 2379
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
