apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amunt0/argocd-apps
    targetRevision: HEAD
    path: configs/tekton/
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
