apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forecastle
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://stakater.github.io/stakater-charts
    chart: forecastle
    targetRevision: v1.0.97
    helm:
      values: |
        forecastle:
          config:
            namespaceSelector:
              matchNames:
                - argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
