# applications/traefik/traefik.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: system
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 24.0.0
    helm:
      values: |
        deployment:
          replicas: 1
        service:
          enabled: true
          type: LoadBalancer  # This will use MetalLB
        ports:
          web:
            port: 80
            expose: true
            exposedPort: 80
            protocol: TCP
          websecure:
            port: 443
            expose: true
            exposedPort: 443
            protocol: TCP
        ingressRoute:
          dashboard:
            enabled: true
        experimental:
          plugins:
            enabled: true
        logs:
          general:
            level: INFO
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
