apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-provider-gcp
  namespace: argocd
spec:
  project: system
  source:
    repoURL: https://github.com/amunt0/argocd-apps
    targetRevision: HEAD
    path: configs/crossplane/
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane
  syncPolicy:
    automated:
      prune: true
      selfHeal: true



