apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tdx-apps
  namespace: argocd
spec:
  project: apps
  source:
    repoURL: https://github.com/amunt0/argocd-apps
    targetRevision: HEAD
    path: configs/tdx-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: tdx-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
