apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
  - https://storage.googleapis.com/tekton-releases/triggers/latest/release.yaml
  - https://storage.googleapis.com/tekton-releases/triggers/latest/interceptors.yaml
  - https://storage.googleapis.com/tekton-releases/dashboard/latest/release-full.yaml

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: tekton-pipelines-controller
      namespace: tekton-pipelines
    spec:
      template:
        spec:
          containers:
            - name: tekton-pipelines-controller
              env:
                - name: KUBERNETES_MIN_VERSION
                  value: "1.20.15"
              resources:
                requests:
                  cpu: 10m
                  memory: 128M
                limits:
                  cpu: 100m
                  memory: 1024M
