apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-custom-settings
  namespace: dns
data:
  FTLCONF_LOCAL_IPV4: "0.0.0.0"
  WEB_PORT: "80"
  DNS_BOGUS_PRIV: "true"
  DNS_FQDN_REQUIRED: "true"
  DNSSEC: "true"
  CONDITIONAL_FORWARDING: "false"
  WEBPASSWORD: "changeme" 
  TZ: "UTC"
  # Add these for .home domain
  PIHOLE_DOMAIN: "home"
  DHCP_ACTIVE: "false"
  REV_SERVER: "true"
  REV_SERVER_CIDR: "192.168.0.0/16"
  REV_SERVER_TARGET: "192.168.68.1"  # Your router's IP
  REV_SERVER_DOMAIN: "home"
