apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fhevm-indexer-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
