apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  namespace: downloader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaresolverr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      containers:
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:latest
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: TZ
              value: "Etc/UTC"
            - name: CAPTCHA_SOLVER
              value: "none"
            - name: PORT
              value: "8191"
          ports:
            - containerPort: 8191
              name: web
              protocol: TCP
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  namespace: downloader
  labels:
    app: flaresolverr
spec:
  type: ClusterIP
  ports:
    - port: 8191
      targetPort: 8191
      name: web
      protocol: TCP
    - port: 80
      targetPort: 8191
      name: http
      protocol: TCP
    - port: 443
      targetPort: 8191
      name: https
      protocol: TCP
  selector:
    app: flaresolverr
