apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  namespace: downloader
  labels:
    app: jackett
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jackett
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jackett
    spec:
      containers:
        - name: jackett
          image: linuxserver/jackett:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
            - name: UMASK
              value: "022"
            - name: AUTO_UPDATE
              value: "true"
          ports:
            - containerPort: 9117
              name: web
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /UI/Login
              port: 9117
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /UI/Login
              port: 9117
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jackett-config-pvc
        - name: downloads
          hostPath:
            path: /mnt/ssd/downloads
            type: Directory
