
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloader
resources:
  - sonarr.yaml
  - radarr.yaml
  - prowlarr.yaml
  - jackett.yaml  
  - flaresolverr.yaml  
  - pvc.yaml
