apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent-vpn
  namespace: media
  labels:
    app: qbittorrent-vpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent-vpn
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: qbittorrent-vpn
    spec:
      # Let's try a different approach - using a single VPN container with sidecar proxies
      containers:
        - name: nordvpn
          image: ghcr.io/bubuntux/nordvpn:v3.12.3
          securityContext:
            privileged: true  # Required for VPN functionality
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: nordvpn-credentials
                  key: NORDVPN_TOKEN
            - name: CONNECT
              value: "Netherlands"  # Connect to Netherlands servers
            - name: TECHNOLOGY
              value: "NordLynx"
            - name: NETWORK
              value: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
            - name: DNS
              value: "1.1.1.1,1.0.0.1"  # Cloudflare DNS for better reliability
            - name: TZ
              value: "Etc/UTC"
            # Add ports we want to expose from qBittorrent
            - name: PORTS
              value: "8080"  # qBittorrent WebUI port
          ports:
            - containerPort: 8080  # Expose qBittorrent WebUI through VPN
              name: webui
          volumeMounts:
            - name: dev-tun
              mountPath: /dev/net/tun
            - name: nordvpn-config
              mountPath: /run/nordvpn
            # Mount qBittorrent config and data volumes
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: movies
              mountPath: /mnt/movies
            - name: series
              mountPath: /mnt/tv

        # Add a sidecar container with qBittorrent using the host network
        - name: qbittorrent
          image: linuxserver/qbittorrent:latest
          # Use host networking to avoid the PID 1 issue
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
            - name: WEBUI_PORT
              value: "8080"
            - name: WEBUI_ADDRESS
              value: "0.0.0.0"  # Listen on all interfaces
            - name: UMASK
              value: "022"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: movies
              mountPath: /mnt/movies
            - name: series
              mountPath: /mnt/tv
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "ps aux | grep -v grep | grep -q qbittorrent-nox"
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 5
          
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
        - name: downloads
          emptyDir: {}
        - name: movies
          hostPath:
            path: /mnt/minio/movies
            type: Directory
        - name: series
          hostPath:
            path: /mnt/minio/series
            type: Directory
        - name: dev-tun
          hostPath:
            path: /dev/net/tun
        - name: nordvpn-config
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: media
  labels:
    app: qbittorrent-vpn
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 8080
      targetPort: 8080
  selector:
    app: qbittorrent-vpn
