apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent-vpn
  namespace: media
  labels:
    app: qbittorrent-vpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent-vpn
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: qbittorrent-vpn
    spec:
      # Using a single container approach with VPN sidecar
      containers:
        - name: qbittorrent-nordvpn
          image: ghcr.io/wfg/qbittorrent-nordvpn:latest
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
          env:
            # NordVPN settings
            - name: NORDVPN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: nordvpn-credentials
                  key: NORDVPN_TOKEN
            - name: SERVER
              value: "nl"  # Netherlands servers
            - name: PROTOCOL
              value: "nordlynx"
            - name: CATEGORY
              value: "p2p"
            - name: FIREWALL
              value: "true"
            - name: LAN_NETWORK
              value: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
            
            # qBittorrent settings
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
            - name: WEBUI_PORT
              value: "8080"
            - name: UMASK_SET
              value: "022"
          ports:
            - containerPort: 8080
              name: webui
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: movies
              mountPath: /mnt/movies
            - name: series
              mountPath: /mnt/tv
            - name: dev-tun
              mountPath: /dev/net/tun
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 2Gi
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 5
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
        - name: downloads
          emptyDir: {}
        - name: movies
          hostPath:
            path: /mnt/minio/movies
            type: Directory
        - name: series
          hostPath:
            path: /mnt/minio/series
            type: Directory
        - name: dev-tun
          hostPath:
            path: /dev/net/tun
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: media
  labels:
    app: qbittorrent-vpn
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 8080
      targetPort: 8080
  selector:
    app: qbittorrent-vpn
