apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent-vpn
  namespace: media
  labels:
    app: qbittorrent-vpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent-vpn
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: qbittorrent-vpn
      annotations:
        container.apparmor.security.beta.kubernetes.io/nordvpn: unconfined
    spec:
      # This is critical - it makes containers share the network namespace
      shareProcessNamespace: true
      
      containers:
        - name: nordvpn
          image: ghcr.io/bubuntux/nordvpn:v3.12.3
          securityContext:
            privileged: true  # Required for VPN functionality
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: nordvpn-credentials
                  key: NORDVPN_TOKEN
            - name: CONNECT
              value: "ro"  # Romania servers
            - name: TECHNOLOGY
              value: "NordLynx"  # Using NordLynx for better performance
            - name: NETWORK
              value: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"  # Allow access from k8s networks
            - name: TZ
              value: "Etc/UTC"
          volumeMounts:
            - name: dev-tun
              mountPath: /dev/net/tun
            - name: nordvpn-data
              mountPath: /var/lib/nordvpn
          # Important: Container needs to be ready before qBittorrent starts
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - nordvpn status | grep -q 'Connected'
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 10

        - name: qbittorrent
          image: linuxserver/qbittorrent:latest
          # Important: This makes qBittorrent wait for nordvpn to be ready
          startupProbe:
            exec:
              command:
                - sh
                - -c
                - "cat /proc/net/route | grep tun"
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
            - name: WEBUI_PORT
              value: "8080"
            - name: UMASK
              value: "022"
          ports:
            - containerPort: 8080
              name: webui
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: movies
              mountPath: /mnt/movies
            - name: series
              mountPath: /mnt/tv
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 2Gi
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 5
            
      # Use init container to set up proper network routing
      initContainers:
        - name: init-network
          image: busybox
          command: ['sh', '-c', 'echo "Setting up network routing for VPN"']
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
      
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
        - name: downloads
          emptyDir: {}
        - name: movies
          hostPath:
            path: /mnt/minio/movies
            type: Directory
        - name: series
          hostPath:
            path: /mnt/minio/series
            type: Directory
        - name: dev-tun
          hostPath:
            path: /dev/net/tun
        - name: nordvpn-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: media
  labels:
    app: qbittorrent-vpn
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 8080
      targetPort: 8080
  selector:
    app: qbittorrent-vpn
