apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: downloader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: linuxserver/radarr:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
            - name: UMASK
              value: "022"
          ports:
            - containerPort: 7878
              name: web
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: movies
              mountPath: /movies
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 1Gi
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: radarr-config-pvc
        - name: downloads
          hostPath:
            path: /mnt/ssd/downloads
        - name: movies
          hostPath:
            path: /mnt/minio/movies
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: downloader
  labels:
    app: radarr
spec:
  type: ClusterIP
  ports:
    - port: 7878
      targetPort: 7878
      name: web
  selector:
    app: radarr
---
apiVersion: v1
kind: Service
metadata:
  name: radarr-server-lb
  namespace: downloader
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "radarr.home"
    external-dns.alpha.kubernetes.io/ingress-hostname-source: "service-annotation-only"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 7878
      name: http
    - port: 443
      targetPort: 7878
      name: https
  selector:
    app: radarr
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr
  namespace: downloader
  annotations:
    cert-manager.io/cluster-issuer: "selfsigned-issuer"
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
    external-dns.alpha.kubernetes.io/enabled: "true"
    external-dns.alpha.kubernetes.io/hostname: "radarr.home"
    external-dns.alpha.kubernetes.io/ttl: "60"
    traefik.ingress.kubernetes.io/preserve-host: "true"
    traefik.ingress.kubernetes.io/pass-client-headers: "true"
spec:
  tls:
    - hosts:
        - radarr.home
      secretName: radarr-tls
  rules:
    - host: radarr.home
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: radarr
                port:
                  number: 7878