apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: media
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  # No selector needed as we're using custom endpoints
---
apiVersion: v1
kind: Endpoints
metadata:
  name: qbittorrent
  namespace: media
subsets:
  - addresses:
    - ip: 192.168.68.64  # The IP address of your host running Docker Compose
    ports:
    - port: 8080
      name: web
