apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: evm-indexer
  namespace: argo-system
spec:
  project: apps
  source:
    repoURL: https://github.com/amunt0/argocd-apps 
    targetRevision: HEAD
    path: configs/indexer/
    helm:
      values: |
        image:
          repository: ghcr.io/amunt0/evm-indexer
          tag: latest
        indexer:
          rpcEndpoint: ""          # Will be set in ArgoCD
          blocksInMemory: 1000     # Default value
          rotationBlocks: 10000    # Default value
          metricsPort: 9090       # Default value
          startBlock: 0           # Will be set in ArgoCD
  destination:
    server: https://kubernetes.default.svc
    namespace: fhevm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
