# configs/tdx-apps/configmaps.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: covalidator-config
  namespace: tdx-apps
data:
  covalidator.toml: |
    HostChainRpcUrl = "https://base-sepolia.g.alchemy.com/v2/HWGi2fVKYhTkhHLTxNWWPrgj2YdlJuXq"
    L1Enabled = false
    ComputeType = 0
    IncoExecutorAddr = "0x0C890f89962660CeAD67dA3D6121e43ffbdc74C3"
    HostChainId = 11155111
    CovalidatorName = "covalidator"
    GrpcServerAddress = "0.0.0.0:50055"
    BlockOffsetDir = "/root"
    RequestCounterDir = "/root"
    ECIESPrivateKey = "0x587da1e3c889f9e3852ab593852ad520f296281d1af303136b7421e31250c34d"
    IncoExecutorType = "IncoLite"
    ExposeKMSService = true
    DecryptionHandlerAddr = "0x0C890f89962660CeAD67dA3D6121e43ffbdc74C3"
    CallbackPrivateKey = "de5fcdf769b02b4378557f1f17309f9c3537d490e4c8489951d8213a3dea2685"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: covalidator-last-block
  namespace: tdx-apps
data:
  lastBlock.txt: "22323000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: covalidator-request-counter
  namespace: tdx-apps
data:
  requestCounter.txt: "0"
