# configs/tdx-apps/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tdx-workload-sa
  namespace: tdx-apps
  annotations:
    iam.gke.io/gcp-service-account: "tdx-workload@697085482582.iam.gserviceaccount.com"
